behaviors:
  ShooterAgents:
    # trainer_setting
    trainer_type: ppo

    # basic_settings
    max_steps: 500000
    time_horizon: 64
    summary_freq: 1000
    keep_checkpoints: 5
    checkpoint_interval: 500000
    threaded: true

    # hyperparameters_setting
    hyperparameters:
      # PPO_and_SAC_common_settings
      batch_size: 512
      buffer_size: 10240
      learning_rate: 0.0003
      learning_rate_schedule: constant
      
      # PPO_only_settings
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
    
    # neural_network_settings
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple

    # reward_signals_settings
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    
    # self_play_settings
    self_play:
      save_steps: 50000
      team_change: 200000
      swap_steps: 50000
      window: 30
      play_against_latest_model_ratio: 0.5
      initial_elo: 1200.0