behaviors:
  ShooterAgents:
    # trainer_setting
    trainer_type: ppo

    # basic_settings
    max_steps: 2500000
    time_horizon: 1024
    summary_freq: 1000
    keep_checkpoints: 5
    checkpoint_interval: 500000
    threaded: true

    # hyperparameters_setting
    hyperparameters:
      # PPO_and_SAC_common_settings
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 0.001
      learning_rate_schedule: constant
      
      # PPO_only_settings
      beta: 0.001
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
    
    # neural_network_settings
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 3
      vis_encode_type: simple

    # reward_signals_settings
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    
    # self_play_settings
    self_play:
      save_steps: 10000
      team_change: 40000
      swap_steps: 2000
      window: 20
      play_against_latest_model_ratio: 0.5
      initial_elo: 1200.0